services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    restart: unless-stopped
    hostname: keycloak
    depends_on:
      - postgres
      - mailhog
    ports:
      - "9080:8080"
      - "8787:8787"
    healthcheck:
      test: curl -fs http://localhost:8080/health
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - type: bind
        source: ./keycloak/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
        consistency: consistent
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123456
      KC_HTTP_HOST: 0.0.0.0
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: false
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_POOL_MIN_SIZE: 0
      KC_DB_POOL_MAX_SIZE: 10
      KC_DB_POOL_INITIAL_SIZE: 1
      KC_LOG_CONSOLE_COLOR: true
      KC_LOG_LEVEL: INFO
      KC_PROXY: edge
      KC_CACHE: local
      DEBUG: true
      DEBUG_PORT: '*:8787'
      KC_FEATURES: "account-api,account3,authorization,ciba,client-policies,impersonation,par,step-up-authentication,web-authn"
    command: "start-dev --import-realm "
